### ISSUE TITLE
QLPlugin Metadata File

### ISSUE THREAD

**Issue by jeremyhart** [QL-Win/QuickLook.Plugin.HelloWorld#1]
Should QuickLook.Plugin.Metadata.config be included since this is required for a plugin to install?

**Comment by xupefei** [comment]
No, it shouldn't. The real file will be generated by update-version.ps1 at
compile time. This script is invoked from Quickly ok.Common build events.

**Comment by xupefei** [comment]
Typo: ... by QuickLook.Common ...
